version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.12.17
    environment:
      DEFAULT_REGION: us-east-1
      HOST_TMP_FOLDER: /tmp/localstack
      LAMBDA_DOCKER_NETWORK: src-network
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOTE_DOCKER: 1
      LOCALSTACK_API_KEY: $LOCALSTACK_API_KEY
      LS_LOG: trace
      SERVICES: ecr,lambda
    ports:
      - 4566:4566
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: src-network
