#!/bin/bash

FUNCTION_NAME=rapids-v0-hydrator
TIMEOUT=7
VERSION=2021-09-03T12-20-00

DEV_ENVIRONMENT="{
	1MILL_LAMBDA_AWS_ACCESS_KEY_ID=test,
	1MILL_LAMBDA_AWS_ENDPOINT=http://localstack:4566/,
	1MILL_LAMBDA_AWS_REGION=us-east-1,
	1MILL_LAMBDA_AWS_SECRET_ACCESS_KEY=test,
	NODE_ENV=development,
}"
