FROM public.ecr.aws/lambda/nodejs:14

WORKDIR $LAMBDA_TASK_ROOT

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN find . -type d -exec chmod 755 {} \;
RUN find . -type f -exec chmod 644 {} \;

ENV \
	AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	AWS_ENDPOINT=$AWS_ENDPOINT \
	AWS_REGION=$AWS_REGION \
	AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
	FUNCTIONS=$FUNCTIONS \
	FUNCTIONS_DIR=./data \
	NODE_ENV=production

CMD [ "index.handler" ]
