FROM public.ecr.aws/lambda/nodejs:14

WORKDIR $LAMBDA_TASK_ROOT

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN find . -type d -exec chmod 755 {} \;
RUN find . -type f -exec chmod 644 {} \;

ENV \
	FUNCTIONS=$FUNCTIONS \
	FUNCTIONS_DIR=./data \
	INVOKE_AWS_ACCESS_KEY_ID=$INVOKE_AWS_ACCESS_KEY_ID \
	INVOKE_AWS_ENDPOINT=$INVOKE_AWS_ENDPOINT \
	INVOKE_AWS_REGION=$INVOKE_AWS_REGION \
	INVOKE_AWS_SECRET_ACCESS_KEY=$INVOKE_AWS_SECRET_ACCESS_KEY \
	NODE_ENV=production

CMD [ "index.handler" ]
