version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:$TERRAFORM_VERSION
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - $DIR:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
