FROM public.ecr.aws/lambda/nodejs:14

WORKDIR $LAMBDA_TASK_ROOT

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN find . -type d -exec chmod 755 {} \;
RUN find . -type f -exec chmod 644 {} \;

ENV \
	ABLY_API_KEY=$ABLY_API_KEY \
	JOURNAL_DB_NAME=$JOURNAL_DB_NAME \
	JOURNAL_DB_URI=$JOURNAL_DB_URI \
	JOURNAL_TABLE_NAME=$JOURNAL_TABLE_NAME \
	NODE_ENV=production

CMD [ "index.handler" ]
