FROM public.ecr.aws/lambda/nodejs:14

WORKDIR $LAMBDA_TASK_ROOT

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN find . -type d -exec chmod 755 {} \;
RUN find . -type f -exec chmod 644 {} \;

ENV \
	NODE_ENV=production \
	PUSHER_APPID=$PUSHER_APPID \
	PUSHER_CLUSTER=$PUSHER_CLUSTER \
	PUSHER_KEY=$PUSHER_KEY \
	PUSHER_SECRET=$PUSHER_SECRET

CMD [ "index.handler" ]
