version: '3.8'

services:
  admin:
    image: mongo-express:latest
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo-able:27017/
    ports:
      - 8081:8081
    restart: always

  mongo:
    image: mongo:5.0.2
    environment:
      MONGO_INITDB_DATABASE: development
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: root
    networks:
      default:
        aliases:
          - mongo-able
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-volume:/data/db

networks:
  default:
    name: src-network

volumes:
  mongo-volume: {}
